import { z } from "zod";

export const httpErrorCodeSchema = z.enum([
  "run_not_found",
  "debate_not_found",
  "artifact_not_found",
  "missing_artifact_content",
  "provider_not_found",
  "runtime_not_found",
  "runtime_mode_not_found",
  "model_not_found",
  "message_not_found",
  "memory_not_found",
  "evidence_not_found",
  "approval_not_found",
  "tool_invocation_not_found",
  "approval_not_pending",
  "tool_run_required",
  "tool_target_invalid",
  "tool_target_mismatch",
  "tool_hosted_auth_required",
  "tool_store_unavailable",
  "tool_dispatch_unavailable",
  "tool_dispatch_failed",
  "tool_dispatch_retry_exhausted",
  "tool_policy_denied",
  "tool_policy_config_invalid",
  "tool_policy_failed",
  "tool_real_tools_disabled",
  "tool_hosted_tools_disabled",
  "tool_connected_node_tools_disabled",
  "tool_approval_required",
  "tool_approval_rejected",
  "tool_approval_expired",
  "tool_adapter_unavailable",
  "tool_input_limit_exceeded",
  "tool_concurrency_limit_exceeded",
  "tool_output_limit_exceeded",
  "tool_artifact_write_failed",
  "tool_redaction_failed",
  "tool_worker_restarted",
  "tool_node_unavailable",
  "tool_node_execution_failed",
  "tool_assignment_expired",
  "tool_assignment_mismatch",
  "hosted_runtime_approval_bridge_unshipped",
  "hosted_runtime_bridge_store_unavailable",
  "hosted_runtime_bridge_queue_unavailable",
  "hosted_runtime_bridge_worker_unavailable",
  "hosted_runtime_bridge_operation_unsupported",
  "hosted_runtime_bridge_session_missing",
  "hosted_runtime_bridge_session_not_owned",
  "hosted_runtime_session_missing",
  "hosted_runtime_session_lost",
  "hosted_runtime_session_state_incomplete",
  "hosted_runtime_bridge_payload_mismatch",
  "hosted_runtime_bridge_command_expired",
  "hosted_runtime_bridge_non_idempotent_retry_blocked",
  "hosted_runtime_bridge_quota_exceeded",
  "hosted_codex_interactive_unshipped",
  "codex_exec_json_input_unsupported",
  "codex_exec_json_approval_bridge_unsupported",
  "acp_permission_request_invalid",
  "acp_permission_response_failed",
  "acp_permission_request_expired",
  "acp_prompt_in_flight",
  "acp_session_not_ready_for_input",
  "agentfield_bridge_unshipped",
  "generic_http_bridge_unshipped",
  "approval_scope_denied",
  "repo_hosted_unshipped",
  "browser_tool_unshipped",
  "fetch_url_invalid",
  "fetch_host_not_allowlisted",
  "fetch_private_network_denied",
  "fetch_redirect_denied",
  "fetch_method_denied",
  "fetch_content_type_denied",
  "web_search_provider_unconfigured",
  "web_search_query_invalid",
  "github_token_missing",
  "github_repo_not_allowlisted",
  "github_operation_denied",
  "github_not_found",
  "github_rate_limited",
  "repo_cwd_denied",
  "repo_operation_denied",
  "repo_pathspec_invalid",
  "shell_command_denied",
  "shell_command_not_configured",
  "tool_process_spawn_failed",
  "tool_process_nonzero_exit",
  "tool_process_timeout",
  "tool_process_cancelled",
  "approval_required",
  "unsupported_tool",
  "invalid_input",
  "invalid_query",
  "adapter_protocol_failed",
  "internal_error",
  "placement_denied",
  "node_auth_required",
  "node_auth_failed",
  "node_not_found",
  "assignment_not_found",
  "assignment_claim_conflict",
  "node_policy_denied",
  "queue_unavailable",
  "event_sync_gap",
  "event_sync_conflict",
  "object_store_unavailable",
  "object_store_timeout",
  "object_store_auth_failed",
  "object_store_bucket_not_found",
  "object_store_read_failed",
  "artifact_digest_mismatch",
  "artifact_content_empty",
  "artifact_sync_failed",
  "hosted_runtime_not_allowed",
  "payload_too_large",
  "auth_required",
  "auth_failed",
  "auth_conflict",
  "auth_store_unavailable",
  "tenant_access_denied",
  "project_access_denied",
  "entitlement_denied",
  "quota_exceeded",
  "audit_log_unavailable"
]);

export const R18_HTTP_ERROR_CODES = [
  "auth_required",
  "auth_failed",
  "auth_conflict",
  "auth_store_unavailable",
  "tenant_access_denied",
  "project_access_denied",
  "entitlement_denied",
  "quota_exceeded",
  "audit_log_unavailable"
] as const satisfies readonly z.infer<typeof httpErrorCodeSchema>[];

export const httpErrorDetailSchema = z.object({
  path: z.string().min(1),
  issue: z.string().min(1)
});

export const httpErrorEnvelopeSchema = z.object({
  error: z.object({
    code: httpErrorCodeSchema,
    message: z.string().min(1),
    details: z.array(httpErrorDetailSchema).optional(),
    requestId: z.string().min(1).optional()
  })
});

export type HttpErrorCode = z.infer<typeof httpErrorCodeSchema>;
export type HttpErrorDetail = z.infer<typeof httpErrorDetailSchema>;
export type HttpErrorEnvelope = z.infer<typeof httpErrorEnvelopeSchema>;
